# Generated by Django 6.1.1 on 2026-09-25 18:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('frequency_type', models.CharField(choices=[('DAILY', 'Daily'), ('INTERVAL_DAYS', 'Every X days'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('frequency_interval', models.PositiveIntegerField(default=1, help_text='Number of days or weeks between occurrences; monthly uses months.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='chores.household')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChoreRotationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField()),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_members', to='chores.chore')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_rotations', to='chores.householdmembership')),
            ],
            options={
                'ordering': ['sequence_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('chore', 'membership'), name='unique_chore_rotation_member'), models.UniqueConstraint(fields=('chore', 'sequence_order'), name='unique_chore_rotation_order')],
            },
        ),
    ]
