# Generated by Django 6.1.1 on 2026-09-25 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_choreassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REMINDER', 'Due reminder'), ('OVERDUE', 'Overdue alert')], max_length=12)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='chores.choreassignment')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chores.household')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='chores_noti_recipie_85d31d_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'assignment', 'notification_type'), name='unique_recipient_assignment_notification')],
            },
        ),
    ]
